services:
    agit.settings:
        class: Agit\SettingBundle\Service\SettingService
        arguments: [ @agit.pluggable.entity.loader_factory, @doctrine.orm.entity_manager ]
        tags: [{ name: agit.pluggable, type: entity, tag: agit.setting, entity: AgitSettingBundle:Setting, baseClass: Agit\SettingBundle\Plugin\AbstractSetting }]
