services:
    agit.setting:
        class: Agit\SettingBundle\Service\SettingService
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags: [{ name: kernel.event_listener, event: agit.seed, method: registerSeed }]

    agit.setting.seed.usercapability:
        private: true
        class: Agit\SettingBundle\Service\UserCapabilitySeed
        tags: [{ name: kernel.event_listener, event: agit.seed, method: registerSeed }]

    agit.setting.twig:
        class: Agit\SettingBundle\Service\SettingsExtension
        arguments:  [ "@agit.setting" ]
        tags: [{ name: twig.extension }]
